hazelcast-client:
  network:
    cluster-members:
      - localhost:5701
  connection-strategy:
    async-start: false
    reconnect-mode: ON
    connection-retry:
      initial-backoff-millis: 5000   # 5 segundos
      max-backoff-millis: 1800000      # 30 minutos
      multiplier: 1
      cluster-connect-timeout-millis: 1800000
      jitter: 0.2
